services:
  postgres:
    image: 'postgres:18.1'
    environment:
      - 'POSTGRES_DB=todobot'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=todo'
    ports:
      - '5432:5432' # Expose PostgreSQL port to the host machine
